import type { HistoricalMedia } from '../data/media';
import type { HistoricalSource } from '../data/sources';
import type { VisualActivity } from '../data/visualActivities';

export const PeriodBadge = ({ period }: { period: string }) => <span className="rounded-full bg-amber-100 text-amber-900 px-3 py-1 text-xs font-semibold">{period}</span>;
export const SearchBar = ({ value, onChange }: { value: string; onChange: (v: string) => void }) => <input aria-label="Cercador" value={value} onChange={(e) => onChange(e.target.value)} placeholder="Cerca per títol o paraula clau..." className="w-full rounded-xl border px-4 py-2 bg-white/90" />;
export const FilterPanel = ({ options, value, onChange }: { options: string[]; value: string; onChange: (v: string) => void }) => <select value={value} onChange={(e) => onChange(e.target.value)} className="rounded-xl border px-3 py-2">{options.map(o => <option key={o}>{o}</option>)}</select>;
export const ProgressCard = ({ progress }: { progress: number }) => <div className="card"><h3 className="font-semibold mb-2">Progrés global</h3><div className="w-full h-3 bg-slate-200 rounded-full"><div className="h-3 bg-emerald-600 rounded-full" style={{ width: `${progress}%` }} /></div><p className="text-sm mt-2">{progress}% completat</p></div>;
export const HistoricalImageCard = ({ image }: { image: HistoricalMedia }) => <article className="card"><img src={image.imageUrl} alt={image.altText} className="w-full h-44 object-cover rounded-lg"/><h4 className="font-semibold mt-2">{image.title}</h4><p className="text-xs text-slate-600">{image.date} · {image.sourceName}</p><p className="text-sm mt-1">{image.description}</p></article>;
export const ImageGallery = ({ items }: { items: HistoricalMedia[] }) => <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{items.map(i => <HistoricalImageCard key={i.id} image={i} />)}</div>;
export const SourceCard = ({ source }: { source: HistoricalSource }) => <article className="card"><h4 className="font-semibold">{source.title}</h4><p className="text-xs">{source.date} · {source.author}</p><p className="mt-2 text-sm">{source.excerpt}</p></article>;
export const SourceViewer = ({ source }: { source: HistoricalSource }) => <div className="card"><h3 className="font-semibold">{source.title}</h3><p className="text-sm">{source.historicalContext}</p><ul className="list-disc ml-5 text-sm mt-2">{source.mainIdeas.map((m, i) => <li key={i}>{m}</li>)}</ul><p className="text-sm mt-2"><strong>Model:</strong> {source.modelCommentary}</p></div>;
export const VisualActivityCard = ({ activity }: { activity: VisualActivity }) => <article className="card"><h4 className="font-semibold">{activity.title}</h4><p className="text-xs">{activity.period} · {activity.difficulty}</p><img src={activity.imageUrl} alt={activity.title} className="mt-2 h-40 w-full object-cover rounded"/><ul className="list-disc ml-5 text-sm mt-2">{activity.questions.map((q, i) => <li key={i}>{q}</li>)}</ul></article>;
export const TimelineEventCard = ({ date, title, description, imageUrl }: { date: string; title: string; description: string; imageUrl?: string }) => <article className="card"><div className="flex gap-3">{imageUrl && <img src={imageUrl} alt={title} className="w-20 h-20 object-cover rounded"/>}<div><p className="text-xs text-slate-500">{date}</p><h4 className="font-semibold">{title}</h4><p className="text-sm">{description}</p></div></div></article>;
export const TopicHero = ({ title, subtitle, imageUrl }: { title: string; subtitle: string; imageUrl?: string }) => <section className="card bg-gradient-to-r from-sky-900 to-rose-900 text-white"><h2 className="text-2xl font-bold">{title}</h2><p className="opacity-90">{subtitle}</p>{imageUrl && <img src={imageUrl} alt={title} className="w-full mt-4 h-52 object-cover rounded-lg"/>}</section>;
